### ISSUE TITLE
Can't see some old skool text in dark mode

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/PredBat-Table-Card#13]
In dark mode the Idle Eco or Idle battery empty, you can't see the arrows in black on black/grey background 

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/4b754b99-b9eb-421e-a958-7e8e95d239d2)

Also, if it is possible to detect the screen size I'd like the idea of truncating the Charging Discharging statii on narrow screens such as mobile. Would get more on the screen and reduce having to scroll horizontally

**Comment by pacemaker82** [comment]
[Version 1.4.5 is out](https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.4.5) that should tackle these issues

<img width="403" alt="Screenshot 2024-03-10 at 08 53 30" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/54904b3d-ab02-48a8-a4cc-800eb5b4ec78">

**Comment by pacemaker82** [comment]
Managed to shave a bit more off. It actually wont make a difference to truncate the other strings, this is the smallest I can go with the two truncated strings side by side with the icons.

Will push this in the next release.

<img width="405" alt="Screenshot 2024-03-10 at 09 10 19" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/4b5f8eaa-d6d4-4418-9c08-8ebc56e76f72">

**Comment by gcoan** [comment]
On 1.4.5 the non truncated text is looking great. Possibly because the agile rates are rubbish tonight and tomorrow so there's no planned discharge at all and it fits very nicely on one line 

Arrows show up fine now in dark mode 

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/9e4e65f7-6b2b-4c07-9eff-5719024f02be)

**Comment by pacemaker82** [comment]
Yeah - there's only so much I can do in terms of phone width and the amount of data the table shows. At the end of the day the user is going to have to make a choice around more info more side scrolling or less info and less side scrolling. 

Potentially could consider only showing certain columns for mobile (being a YAML configuration item), but even that isn't a guarantee it'll all fit unfortunately. But I do like the idea that I see all columns on my big screen and maybe only the critical on mobile... At the moment my choices have a good mix that just about fits but it does look a bit empty on PC screen

**Comment by pacemaker82** [comment]
I just [pushed 1.4.6](https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.4.6) which shaves off a bit more of the state column width on mobile, as well as fixes some colour issues with the forced idle/charge/discharge now colouring correctly (upside down F scenario)

**Comment by pacemaker82** [comment]
@gcoan actually you can do this with the conditional card (switch between mobile/bigger):

```
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - condition: screen
        media_query: '(min-width: 0px) and (max-width: 767px)'
    card:
      type: custom:predbat-table-card
      entity: predbat.plan_html
      columns:
        - time-column
        - soc-column
        - state-column
        - limit-column
        - total-column
      odd_row_colour: '#181f2a'
      even_row_colour: '#2a3240'
      fill_empty_cells: true
      stack_pills: false
      old_skool_columns:
        - soc-column
        - state-column
  - type: conditional
    conditions:
      - condition: screen
        media_query: '(min-width: 768px)'
    card:
      type: custom:predbat-table-card
      entity: predbat.plan_html
      columns:
        - time-column
        - import-column
        - state-column
        - limit-column
        - soc-column
        - pv-column
        - load-column
        - car-column
        - cost-column
        - total-column
      odd_row_colour: '#181f2a'
      even_row_colour: '#2a3240'
      fill_empty_cells: true
      stack_pills: false
      old_skool_columns:
        - soc-column
        - state-column
```
![IMG_D1EF0A21CA2E-1](https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/434e9d23-6ed1-4d04-bc14-aa5b4b8e859b)

<img width="1331" alt="Screenshot 2024-03-11 at 09 51 40" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/7dfd023b-6a73-4985-8e4f-ffff46f8083a">
