### ISSUE TITLE
Issue with PredBat-Table-Card and Bubblecard

### ISSUE THREAD

**Issue by sakroyd** [pacemaker82/PredBat-Table-Card#39]
I have a dashboard using bubblecard buttons, essentially a vertical stack card containing a bubble-card popup, and then a card with just the PredBat-Table-Card in it.

The bubble-card works fine, until I paste my config for the PredBat-Table-Card as below, and then essentially I see the bubble-card popup and disappear leaving just the blurred dash behind. This only happens with this card, which is super frustrating because its so good. 

Can you help please?

type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#solar'
    button_type: name
    name: Solar
    icon: mdi:solar-panel
  - type: custom:predbat-table-card
    entity: predbat.plan_html
    columns:
      - time-column
      - state-column
      - pv-column
      - load-column
      - soc-column
      - cost-column
      - total-column
    table_width: 60
    fill_empty_cells: false

**Comment by pacemaker82** [comment]
Might need your help because I tried this and nothing works (even the bubble card YAML doesnt work on its own without predbat). This is what I am using:

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#solar'
    button_type: name
    name: Solar
    icon: mdi:solar-panel
  - type: custom:predbat-table-card
    entity: predbat.plan_html
    columns:
      - time-column
      - state-column
      - pv-column
      - load-column
      - soc-column
      - cost-column
      - total-column
    table_width: 60
    fill_empty_cells: false
```

Even just trying this shows nothing in the dashboard:

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#solar'
    button_type: name
    name: Solar
    icon: mdi:solar-panel
```
