### ISSUE TITLE
Issue with display of limit column.

### ISSUE THREAD

**Issue by SwiftRR** [pacemaker82/PredBat-Table-Card#46]
See below (unless it is my yaml coding for your card):
Same issue on iPhone, iPad and Mac.

<img width="555" alt="Image" src="https://github.com/user-attachments/assets/22791969-0bee-49a3-81d2-a81b4785f729" />

Rob

**Comment by pacemaker82** [comment]
Could you show me what the original predbat table shows?

**Comment by SwiftRR** [comment]
It may be easier to show my yaml.
Is the problem that I have switch.predbat_plan_debug set to true (nearly at bottom of predbat webUI) so there is more to fit in the circle. I have tried changing the switch to false and there isn't the problem.
See the screenshot below my yaml with the with set as false.
```
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - condition: screen
        media_query: "(min-width: 0px) and (max-width: 767px)"
    card:
      type: custom:predbat-table-card
      entity: predbat.plan_html
      columns:
        - time-column
        - import-column
        - state-column
        - soc-column
        - limit-column
        - pv-column
        - load-column
        - total-column
      odd_row_colour: "#181f2a"
      even_row_colour: "#2a3240"
      fill_empty_cells: true
      stack_pills: true
      old_skool_columns:
        - soc-column
        - state-column
      hide_empty columns: true
  - type: conditional
    conditions:
      - condition: screen
        media_query: "(min-width: 768px)"
    card:
      type: custom:predbat-table-card
      entity: predbat.plan_html
      columns:
        - time-column
        - import-column
        - state-column
        - limit-column
        - soc-column
        - pv-column
        - load-column
        - car-column
        - cost-column
        - total-column
      odd_row_colour: "#181f2a"
      even_row_colour: "#2a3240"
      fill_empty_cells: true
      stack_pills: true
      old_skool_columns:
        - soc-column
        - state-column
      hide_empty columns: true
      use_friendly_states: true
grid_options:
  columns: full
```

<img width="560" alt="Image" src="https://github.com/user-attachments/assets/b0c50c4a-5e2b-45ac-ad4b-143428e9f1d3" />
