### ISSUE TITLE
Cannot read properties of null (reading '2')

### ISSUE THREAD

**Issue by godfreym29** [pacemaker82/PredBat-Table-Card#49]
when using the examples in the README.md
the following message is displayed `Cannot read properties of null (reading '2')`
If I remove `- limit-column` from `columns:`  then the table is rendered OK

**Comment by pacemaker82** [comment]
Please can you provide the YAML that is not working?

**Comment by godfreym29** [comment]
Running the latest version - 1.5.6.5
The issue is on android companion app and on PC with chrome (up to date)

```
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - condition: screen
        media_query: "(min-width: 0px) and (max-width: 767px)"
    card:
      type: custom:predbat-table-card
      entity: predbat.plan_html
      columns:
        - time-column
        - soc-column
        - state-column
        - limit-column
        - total-column
      odd_row_colour: "#181f2a"
      even_row_colour: "#2a3240"
      fill_empty_cells: true
      stack_pills: false
      old_skool_columns:
        - soc-column
        - state-column
  - type: conditional
    conditions:
      - condition: screen
        media_query: "(min-width: 768px)"
    card:
      type: custom:predbat-table-card
      entity: predbat.plan_html
      columns:
        - time-column
        - import-column
        - state-column
        - limit-column
        - soc-column
        - pv-column
        - load-column
        - car-column
        - cost-column
        - total-column
      odd_row_colour: "#181f2a"
      even_row_colour: "#2a3240"
      fill_empty_cells: true
      stack_pills: false
      old_skool_columns:
        - soc-column
        - state-column
```

**Comment by godfreym29** [comment]
This renders correctly:

```
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - condition: screen
        media_query: "(min-width: 0px) and (max-width: 767px)"
    card:
      type: custom:predbat-table-card
      entity: predbat.plan_html
      columns:
        - time-column
        - soc-column
        - state-column
        - total-column
      odd_row_colour: "#181f2a"
      even_row_colour: "#2a3240"
      fill_empty_cells: true
      stack_pills: false
      old_skool_columns:
        - soc-column
        - state-column
  - type: conditional
    conditions:
      - condition: screen
        media_query: "(min-width: 768px)"
    card:
      type: custom:predbat-table-card
      entity: predbat.plan_html
      columns:
        - time-column
        - import-column
        - state-column
        - soc-column
        - pv-column
        - load-column
        - car-column
        - cost-column
        - total-column
      odd_row_colour: "#181f2a"
      even_row_colour: "#2a3240"
      fill_empty_cells: true
      stack_pills: false
      old_skool_columns:
        - soc-column
        - state-column
```
