### ISSUE TITLE
Not showing scales symbol on narrow screen

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/PredBat-Table-Card#59]
Table card 1.6.1.0

Just moved back to Agile today since we're now running entire off solar generation, and Agile will give me the occasional price plunge. 

Noticed that whilst the table card with debug shows the? and scales for future predicted Agile prices

![image](https://github.com/user-attachments/assets/8dc284b7-6525-4f83-90d9-331bee808289)

With just the import rate showing (which I use for portrait on my mobile) I don't see these symbols, suggesting that these are correct fixed rates not predictions. 

![image](https://github.com/user-attachments/assets/7af8cfd8-4cc4-42ba-a7b9-0ab52297e725)

Tbh could just show the? or the scales as space is tight, don't need both

**Comment by gcoan** [comment]
narrow screen:
```
type: conditional
conditions:
  - condition: screen
    media_query: "(min-width: 0px) and (max-width: 767px)"
card:
  type: custom:predbat-table-card
  entity: predbat.plan_html
  columns:
    - time-column
    - soc-column
    - state-column
    - limit-column
    - import-column
    - pv-column
    - load-column
    - cost-column
    - total-column
  old_skool_columns:
    - soc-column
    - state-column
  odd_row_colour: "#181f2a"
  even_row_colour: "#2a3240"
  table_width: 100
  stack_pills: false
  force_single_line: true
  fill_empty_cells: true
  show_day_totals: true
```

wide screen:
```
type: conditional
conditions:
  - condition: screen
    media_query: "(min-width: 768px)"
card:
  type: custom:predbat-table-card
  entity: predbat.plan_html
  columns:
    - time-column
    - soc-column
    - state-column
    - limit-column
    - import-column
    - export-column
    - pv-column
    - load-column
    - clip-column
    - cost-column
    - total-column
  old_skool_columns:
    - soc-column
    - state-column
  debug_columns:
    - import-column
    - pv-column
  odd_row_colour: "#181f2a"
  even_row_colour: "#2a3240"
  font_size: 14
  table_width: 100
  fill_empty_cells: true
  stack_pills: false
  show_day_totals: true
```

looks like I am using import_column for both.  It may be the force_single_line: true that's a problem?
