### ISSUE TITLE
Sea-sick with wavy predbat plan

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/PredBat-Table-Card#7]
Trying the new predbat plan, just copied the default config into my existing Predbat plan dashboard, and the result is ... up and down wavy, feeling seasick now !

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/c2e7f93e-30f2-4b32-a8e4-103bb7e7d585)

Here's the YAML from the dashboard:

```yaml
  - title: Agile
    path: octopus-agile-rates
    icon: mdi:currency-gbp
    type: custom:grid-layout
    badges: []
    cards:
      - type: custom:html-template-card
        title: Predbat plan
        ignore_line_breaks: true
        content: |
          {{ state_attr('predbat.plan_html', 'html') }}
      - type: custom:predbat-table-card
        entity: predbat.plan_html
        columns:
          - time-column
          - import-column
          - export-column
          - state-column
          - limit-column
          - pv-column
          - load-column
          - soc-column
          - cost-column
          - total-column
        odd_row_colour: '#181f2a'
        even_row_colour: '#2a3240'
        table_width: 100
        fill_empty_cells: true
      - type: custom:octopus-energy-rates-card
        title: Agile Import Rates
        currentEntity: >-
          event.octopus_energy_electricity_MPAN_current_day_rates
        pastEntity: >-
          event.octopus_energy_electricity_MPAN_previous_day_rates
        futureEntity: >-
          event.octopus_energy_electricity_MPAN_next_day_rates
        cols: 3
        showday: true
        showpast: false
        combinerate: true
        cheapest: true
        unitrate: p
```

As well as the up and down wavyness, the columns don't look well aligned with the column titles?

Great to see that this has been made available as a HACS repository, made it very simple to add to HA.

Thanks

**Comment by pacemaker82** [comment]
Hello - this is very odd. What browser are you using, and version of the card do you have installed? I wonder if the other cards are interfering somehow...

I can see you're using the right latest config with `fill_empty_cells: true` but I don't see those empty cells filled. It should look like this "-" in the empty PV column, like the other empty columns I have here:
<img width="714" alt="Screenshot 2024-02-28 at 13 10 30" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/058414b5-b163-4e28-826f-49bfaf004024">

This makes me wonder if the .js you have is latest as that should work without fail.

**Comment by pacemaker82** [comment]
Oh - and did you upgrade, or this is a new install?

**Comment by pacemaker82** [comment]
For what its worth, I have found (just now after refreshing manically over and over) that HA is loading a previous JS every now and then, which does behave badly. Can you clear browser cache and see if that fixes? I read a lot of trouble with caching and cards, maybe there's a better way to blast through that I will look in to

**Comment by gcoan** [comment]
This was a brand new install, done earlier today, and for which I configured this evening.

Looking in HACS it appears I installed 1.0.3, presumably before 1.0.4 had been released but I just copied the config off the GitHub readme.

Upgraded to 1.0.4, reloaded the browser, looks like it's the same?

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/c28a2cb3-26a5-4b3c-b666-ac90abff8a95)

This is using the HA Companion app on an iPad, so other than pull down to refresh the screen, no way to reload cache etc

Just looked on my iPhone, first time I have looked at the card on my phone (also with the HA companion app) and its the same: status, load and total cost all appear to be top aligned in the table cell rather than centre aligned

**Comment by pacemaker82** [comment]
Its very curious. Here is my iPad running latest HA app and iOS (first edition iPad Pro so some years old)

![IMG_0146](https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/5d4e1f8a-19a2-4e3e-bc3f-5ed4f0f3dc7d)

**Comment by gcoan** [comment]
Created a brand new dashboard with just the card on:

```yaml
views:
  - title: Home
    cards:
      - type: custom:predbat-table-card
        entity: predbat.plan_html
        columns:
          - time-column
          - import-column
          - export-column
          - state-column
          - limit-column
          - pv-column
          - load-column
          - soc-column
          - cost-column
          - total-column
        odd_row_colour: '#181f2a'
        even_row_colour: '#2a3240'
        table_width: 100
        fill_empty_cells: true
```

The horizontal alignment is OK now although the card is displayed wider than its surrounding card holder 
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/ada01ac0-6800-4163-b164-474188c893dd)

That was with the default masonry view type.

I tend to use grid (from the layout card HACS front end).

Changing to that, it works fine:
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/dd1f723b-ca06-4ff4-add2-c4ee227233d6)

**Comment by pacemaker82** [comment]
Thanks yeah, there are too many columns to fit the width of that slim card "holder", so you can remove some, or replace import-column and export-column with import-export-column to get that in a single column at least.

Guess there is an issue there with one of the other cards interacting oddly. I will look into that tomorrow.

**Comment by gcoan** [comment]
OK, I have tracked it down, its an incompatibility between your card and the Octopus energy rate card from HACS.

Two views, first one only your card, second one, both cards.

```yaml
keep_texts_in_tabs:
  enabled: true
views:
  - title: Agile ratecard
    type: custom:grid-layout
    badges: []
    cards:
      - type: custom:predbat-table-card
        entity: predbat.plan_html
        columns:
          - time-column
          - import-column
          - export-column
          - state-column
          - limit-column
          - pv-column
          - load-column
          - soc-column
          - cost-column
          - total-column
        odd_row_colour: '#181f2a'
        even_row_colour: '#2a3240'
        table_width: 100
        fill_empty_cells: true
      - type: custom:octopus-energy-rates-card
        title: Agile Import Rates
        currentEntity: >-
          event.octopus_energy_electricity_mpan_current_day_rates
        pastEntity: >-
          event.octopus_energy_electricity_mpan_previous_day_rates
        futureEntity: >-
          event.octopus_energy_electricity_mpan_next_day_rates
        cols: 3
        showday: true
        showpast: false
        combinerate: true
        cheapest: true
        unitrate: p
  - title: Predbat
    path: octopus-agile-rates
    icon: mdi:currency-gbp
    type: custom:grid-layout
    badges: []
    cards:
      - type: custom:predbat-table-card
        entity: predbat.plan_html
        columns:
          - time-column
          - import-column
          - export-column
          - state-column
          - limit-column
          - pv-column
          - load-column
          - soc-column
          - cost-column
          - total-column
        odd_row_colour: '#181f2a'
        even_row_colour: '#2a3240'
        table_width: 100
        fill_empty_cells: true
```

View 1
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/b67d1c7b-042e-4b7b-af8f-81552bf86282)

View 2
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/a3434fba-6528-4d3a-a89b-09fa66c50029)
